import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import ee_icon from '@/../public/ee_icon.png';
import styled from 'styled-components';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

const LandingPage = styled.div`
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
`;

const ImageContainer = styled.div`
	width: 300px;
	height: auto;
	&:hover {
		cursor: pointer;
		transition: all 0.2s ease-in-out;
		transform: scale(1.1);
	}
`;

export default function Landing() {
	return (
		<>
			<Head>
				<title>English Explorers</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/ee_icon.png' />
			</Head>
			<LandingPage>
				<ImageContainer>
					<Link href='/home'>
						<Image src={ee_icon} alt='EE logo' width={300} height={300} />
					</Link>
				</ImageContainer>
			</LandingPage>
		</>
	);
}
